Use same term for Jira issues

diff --git a/notify-jira-about-contribution/action.yml b/notify-jira-about-contribution/action.yml
--- a/notify-jira-about-contribution/action.yml
+++ b/notify-jira-about-contribution/action.yml
@@ -54,19 +54,19 @@ runs:
         echo "result=${{ env.IS_DEPENDABOT_PULL_REQUEST }}" >> $GITHUB_OUTPUT
 
     - name: Check if Jira issue already exists
-      id: jira-ticket-already-exists
+      id: jira-issue-already-exists
       shell: bash
       run: |
         echo "result=${{ contains(github.event.pull_request.labels.*.name, 'contribution') }}" >> $GITHUB_OUTPUT
 
-    - name: Decide if Jira ticket should be created
+    - name: Decide if Jira issue should be created
       id: should-create-jira-issue
       env:
         IS_TEAM_MEMBER: ${{ fromJson(steps.is-team-member.outputs.result) }}
         IS_DEPENDABOT_PULL_REQUEST: ${{ steps.is-dependabot-pull-request.outputs.result }}
         IS_DRAFT: ${{ fromJson(steps.get-pr.outputs.data).draft }}
         SHOULD_NOTIFY_ABOUT_MAJOR_DEPENDABOT_UPDATES: ${{ inputs.should-notify-about-major-dependabot-updates }}
-        JIRA_ISSUE_ALREADY_EXISTS: ${{ steps.jira-ticket-already-exists.outputs.result }}
+        JIRA_ISSUE_ALREADY_EXISTS: ${{ steps.jira-issue-already-exists.outputs.result }}
         PR_TITLE: ${{ fromJson(steps.get-pr.outputs.data).title }}
       shell: bash
       run: |
@@ -113,30 +113,25 @@ runs:
           exit
         fi
 
-        oldMajor=""
-        newMajor=""
-        extractMajorVersionsFromTitle() {
-          pullRequestTitle=$1
-          echo "Checking if PR is a major update, PR title: $pullRequestTitle"
+        pullRequestTitle="${{ env.PR_TITLE }}"
 
-          # Extract number version using grep utility
-          # For "Bump @cypress/webpack-preprocessor from 5.17.1 to 6.0.1" it returns "5"
-          oldMajor=$(echo "$pullRequestTitle" | grep --only-matching --extended-regexp 'from [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)
-          if [ -z "$oldMajor" ]; then
-            echo "Error: Unable to extract old major version" >&2
-            exit 1
-          fi
+        # Extract major version using grep utility
+        # For "Bump @cypress/webpack-preprocessor from 5.17.1 to 6.0.1" it returns "5"
+        oldMajorVersion=$(echo "$pullRequestTitle" | grep --only-matching --extended-regexp 'from [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)
+        if [ -z "$oldMajorVersion" ]; then
+          echo "Error: Unable to extract old major version" >&2
+          exit 1
+        fi
 
-          # For "Bump @cypress/webpack-preprocessor from 5.17.1 to 6.0.1" it returns "5"
-          newMajor=$(echo "$pullRequestTitle" | grep --only-matching --extended-regexp 'to [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)
-          if [ -z "$newMajor_value" ]; then
-            echo "Error: Unable to extract new major version" >&2
-            exit 1
-          fi
-        }
+        # Extract major version using grep utility
+        # For "Bump @cypress/webpack-preprocessor from 5.17.1 to 6.0.1" it returns "5"
+        newMajorVersion=$(echo "$pullRequestTitle" | grep --only-matching --extended-regexp 'to [0-9]+(\.[0-9]+)?' | cut -d' ' -f2 | cut -d'.' -f1)
+        if [ -z "$newMajorVersion" ]; then
+          echo "Error: Unable to extract new major version" >&2
+          exit 1
+        fi
 
-        extractMajorVersionsFromTitle "${{ env.PR_TITLE }}"
-        if [ "$oldMajor" == "$newMajor" ]; then
+        if [ "$oldMajorVersion" == "$newMajorVersion" ]; then
           echo "Is not a major dependency update pull request"
           echo "result=false" >> $GITHUB_OUTPUT
           exit
@@ -153,7 +148,7 @@ runs:
         repo-token: ${{ inputs.github-token }}
         add-labels: "contribution"
 
-    - name: Create JIRA ticket
+    - name: Create Jira issue
       if: ${{ fromJson(steps.should-create-jira-issue.outputs.result) == true }}
       shell: bash
       env:
